# Debugging LED stim, and doves movie regen
VR March 2026

In [1]:
import retinanalysis as ra

[2026-06-16 12:53:14,777][INFO]: DataJoint 0.14.4 connected to root@127.0.0.1:3306

In [3]:
exp_search = ra.get_datasets_from_protocol_names('doves')
exp_search

Found 3 protocols matching "doves":
['edu.washington.riekelab.rachel.protocols.DovesPerturbationAlpha'
 'edu.washington.riekelab.vyom.protocols.DovesPixBlur'
 'manookinlab.protocols.DovesMovie']

Found 58 experiments, 115 epoch blocks.

,exp_name,datafile_name,NDF,chunk_name,protocol_name,is_mea,data_dir,group_label,experiment_id,protocol_id,group_id,block_id,chunk_id
0,20230614C,data007,0.0,chunk2,manookinlab.protocols.DovesMovie,1,20230614C/data007,doves,1,6,8,8,2
1,20230614C,data022,0.0,chunk3,manookinlab.protocols.DovesMovie,1,20230614C/data022,doves,1,6,22,23,4
2,20230614C,data028,0.0,chunk3,edu.washington.riekelab.vyom.protocols.DovesPi...,1,20230614C/data028,doves pix blur,1,14,27,29,4
3,20230719C,data008,0.0,chunk1,manookinlab.protocols.DovesMovie,1,20230719C/data008,doves repeats,3,6,59,65,7
4,20230719C,data028,0.0,chunk3,manookinlab.protocols.DovesMovie,1,20230719C/data028,doves repeats,3,6,73,84,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,20251215C,data004,1.0,nat_image,manookinlab.protocols.DovesMovie,1,20251215C/data004,doves repeats,166,6,2713,4001,740
111,20260401C,data011,1.0,nat_images,manookinlab.protocols.DovesMovie,1,20260401C/data011,DOVES Repeats,194,6,2985,4766,881
112,20260403C,data004,1.0,nat_images,manookinlab.protocols.DovesMovie,1,20260403C/data004,doves,196,6,3005,4794,891
113,20260410C,data007,0.5,nat_images,manookinlab.protocols.DovesMovie,1,20260410C/data007,doves,198,6,3029,4879,896
114,20260415C,data034,1.0,nat_images,manookinlab.protocols.DovesMovie,1,20260415C/data034,natural,201,6,3060,4935,911

In [4]:
exp_search = exp_search.query('group_label=="doves repeats"')

In [5]:
exp_search

,exp_name,datafile_name,NDF,chunk_name,protocol_name,is_mea,data_dir,group_label,experiment_id,protocol_id,group_id,block_id,chunk_id
3,20230719C,data008,0.0,chunk1,manookinlab.protocols.DovesMovie,1,20230719C/data008,doves repeats,3,6,59,65,7
4,20230719C,data028,0.0,chunk3,manookinlab.protocols.DovesMovie,1,20230719C/data028,doves repeats,3,6,73,84,9
24,20230622C,data043,0.0,chunk1,manookinlab.protocols.DovesMovie,1,20230622C/data043,doves repeats,63,6,1389,2253,156
29,20230802C,data008,0.0,chunk2,manookinlab.protocols.DovesMovie,1,20230802C/data008,doves repeats,66,6,1444,2330,163
30,20230802C,data026,0.0,chunk4,manookinlab.protocols.DovesMovie,1,20230802C/data026,doves repeats,66,6,1460,2348,165
51,20240130C,data024,0.5,chunk4,manookinlab.protocols.DovesMovie,1,20240130C/data024,doves repeats,78,6,1694,2621,217
63,20240401C,data015,0.5,chunk3,manookinlab.protocols.DovesMovie,1,20240401C/data015,doves repeats,87,6,1813,2788,246
66,20240401C,data024,0.5,chunk5,manookinlab.protocols.DovesMovie,1,20240401C/data024,doves repeats,87,6,1822,2797,243
109,20251124C,data018,0.5,doves,manookinlab.protocols.DovesMovie,1,20251124C/data018,doves repeats,162,6,2666,3932,713
110,20251215C,data004,1.0,nat_image,manookinlab.protocols.DovesMovie,1,20251215C/data004,doves repeats,166,6,2713,4001,740

In [11]:
ra.get_exp_summary(exp_search.iat[-1,0])

,exp_name,prep_label,datafile_name,group_label,NDF,chunk_name,protocol_name,duration_minutes,minutes_since_start,start_time,end_time,data_dir,experiment_id,prep_id,group_id,block_id,chunk_id,protocol_id
0,20251215C,Mount1,data000,noise,1.0,chunk1,manookinlab.protocols.SpatialNoise,61.83,61.83,2025-12-15 13:50:45,2025-12-15 14:52:35,20251215C/data000,166,194,2709,3997,742,19
1,20251215C,Mount1,data001,CRF,1.0,chunk1,manookinlab.protocols.ContrastResponseGrating,5.52,68.67,2025-12-15 14:53:54,2025-12-15 14:59:25,20251215C/data001,166,194,2710,3998,742,3
2,20251215C,Mount1,data002,moving bar,1.0,moving_bar,manookinlab.protocols.MovingChromaticBar,15.37,85.00,2025-12-15 15:00:23,2025-12-15 15:15:45,20251215C/data002,166,194,2711,3999,741,8
3,20251215C,Mount1,data003,Present Images,1.0,nat_image,manookinlab.protocols.PresentImages,10.03,105.80,2025-12-15 15:26:31,2025-12-15 15:36:33,20251215C/data003,166,194,2712,4000,740,15
4,20251215C,Mount1,data004,doves repeats,1.0,nat_image,manookinlab.protocols.DovesMovie,11.30,119.10,2025-12-15 15:38:33,2025-12-15 15:49:51,20251215C/data004,166,194,2713,4001,740,6
5,20251215C,Mount1,data005,SV Movies 60,1.0,nat_image,edu.washington.riekelab.vyom.protocols.Present...,12.15,143.27,2025-12-15 16:01:52,2025-12-15 16:14:01,20251215C/data005,166,194,2714,4002,740,80
6,20251215C,Mount1,data006,SV Movies 120,1.0,nat_image,edu.washington.riekelab.vyom.protocols.Present...,40.65,184.77,2025-12-15 16:14:52,2025-12-15 16:55:31,20251215C/data006,166,194,2715,4003,740,80
7,20251215C,Mount1,data007,SV Movies 360,1.0,nat_image,edu.washington.riekelab.vyom.protocols.Present...,34.18,221.02,2025-12-15 16:57:35,2025-12-15 17:31:46,20251215C/data007,166,194,2716,4004,740,80
8,20251215C,Mount1,data008,noise,1.0,chunk2,manookinlab.protocols.SpatialNoise,61.75,285.68,2025-12-15 17:34:41,2025-12-15 18:36:26,20251215C/data008,166,194,2717,4005,739,19
9,20251215C,Mount1,data009,CRF,1.0,chunk2,manookinlab.protocols.ContrastResponseGrating,5.50,292.00,2025-12-15 18:37:15,2025-12-15 18:42:45,20251215C/data009,166,194,2718,4006,739,3
10,20251215C,Mount1,data010,CC Var Mean Spa Noise,1.0,var_mean,edu.washington.riekelab.chris.protocols.Spatia...,30.98,345.87,2025-12-15 19:05:38,2025-12-15 19:36:37,20251215C/data010,166,194,2719,4007,738,74
11,20251215C,Mount1,data011,CC 1D Var Mean Noise,1.0,var_mean,edu.washington.riekelab.chris.protocols.monito...,6.88,353.73,2025-12-15 19:37:36,2025-12-15 19:44:29,20251215C/data011,166,194,2720,4008,738,75
12,20251215C,Mount1,data012,CC Cone Var Mean Flash,1.0,var_mean,edu.washington.riekelab.turner.protocols.varia...,19.68,377.57,2025-12-15 19:48:38,2025-12-15 20:08:19,20251215C/data012,166,194,2721,4009,738,57
13,20251215C,Mount1,data013,ROL Variable Mean Bars 2222,1.0,var_mean,edu.washington.riekelab.rachel.protocols.Varia...,20.73,399.90,2025-12-15 20:09:55,2025-12-15 20:30:39,20251215C/data013,166,194,2722,4010,738,73
14,20251215C,Mount1,data014,noise,1.0,chunk3,manookinlab.protocols.SpatialNoise,61.75,468.03,2025-12-15 20:37:02,2025-12-15 21:38:47,20251215C/data014,166,194,2723,4011,743,19
15,20251215C,Mount1,data015,CRF,1.0,chunk3,manookinlab.protocols.ContrastResponseGrating,5.53,475.22,2025-12-15 21:40:26,2025-12-15 21:45:58,20251215C/data015,166,194,2724,4012,743,3

In [12]:
i = -1
sb = ra.MEAStimBlock(exp_search.iat[i, 0], exp_search.iat[i, 1])

Initializing StimBlock for 20251215C block 4001
For Rig C 20251215C:
Warning: Multiple stage frame rates found for experiment 20251215C: [ 59. 118. 354.]
This could be due to PatternMode usage.
d_display will keep the min: 59.0
{'disp_type': 'LCR', 'mu_per_pixel': 3.34, 'n_ht': 1140, 'n_wt': 1824, 'mean_frame_rate': 59.94154881781792, 'stage_frame_rate': np.float64(59.0)}
Failed to get typing files from nearest noise chunk, error: [Errno 2] No such file or directory: '/home/vyomr/Desktop/data/analysis/20251215C/chunk1'
Failed to get typing files from nearest noise chunk, error: [Errno 2] No such file or directory: '/home/vyomr/Desktop/data/analysis/20251215C/chunk2'
Failed to get typing files from nearest noise chunk, error: [Errno 2] No such file or directory: '/home/vyomr/Desktop/data/analysis/20251215C/chunk3'
Warning, none of the noise chunks in this experiment have typing files, chunk3 is None

In [13]:
sb.d_epoch_block_params

{'amp': 'Amp1',
 'preTime': 250.0,
 'stimTime': 6000.0,
 'tailTime': 500.0,
 'waitTime': 1000.0,
 'freezeFEMs': 0,
 'sampleRate': 1000.0,
 'maskDiameter': 0.0,
 'onlineAnalysis': 'none',
 'stimulusIndices': [2.0, 6.0, 12.0, 15.0, 18.0, 24.0, 30.0, 40.0, 50.0],
 'apertureDiameter': 2000.0,
 'numberOfAverages': 90,
 'interpulseInterval': 0.0,
 'manualMagnification': 4.0}

In [11]:
exp_names = ra.schema.Experiment().fetch('exp_name')
# Filter for those ending in H from this np array
exp_names = exp_names[[en.endswith('H') for en in exp_names.astype(str)]]
ra.get_exp_summary(exp_names[-2])

,exp_name,prep_label,datafile_name,group_label,NDF,chunk_name,protocol_name,duration_minutes,minutes_since_start,start_time,end_time,data_dir,experiment_id,prep_id,group_id,block_id,chunk_id,protocol_id
0,20260417H,Mount1,data000,crf 4 R*/r/s,4.0,chunk1,manookinlab.protocols.ContrastResponseGrating,1.32,1.32,2026-04-17 14:20:33,2026-04-17 14:21:52,20260417H/data000,202,239,3061,4936,914,3
1,20260417H,Mount1,data001,crf 4 R*/r/s,4.0,chunk1,manookinlab.protocols.ContrastResponseGrating,2.33,4.30,2026-04-17 14:22:31,2026-04-17 14:24:51,20260417H/data001,202,239,3061,4937,914,3
2,20260417H,Mount1,data002,spatial noise 4 R*/r/s,4.0,chunk1,manookinlab.protocols.SpatialNoise,18.60,23.73,2026-04-17 14:25:41,2026-04-17 14:44:17,20260417H/data002,202,239,3062,4938,914,19
3,20260417H,Mount1,data003,spatial noise 4 R*/r/s,4.0,chunk1,manookinlab.protocols.SpatialNoise,12.50,36.47,2026-04-17 14:44:31,2026-04-17 14:57:01,20260417H/data003,202,239,3062,4939,914,19
4,20260417H,Mount1,data004,spatial noise 4 R*/r/s,4.0,chunk1,manookinlab.protocols.SpatialNoise,49.43,86.17,2026-04-17 14:57:17,2026-04-17 15:46:43,20260417H/data004,202,239,3062,4940,914,19
5,20260417H,Mount1,data005,paired bars and gain 2 R*,4.0,bars_gain,edu.washington.riekelab.rachel.protocols.BarsA...,115.58,214.47,2026-04-17 15:59:26,2026-04-17 17:55:01,20260417H/data005,202,239,3063,4941,915,76
6,20260417H,Mount1,data006,paired bars and gain 2 R*,4.0,bars_gain,edu.washington.riekelab.rachel.protocols.BarsA...,49.58,270.90,2026-04-17 18:01:52,2026-04-17 18:51:27,20260417H/data006,202,239,3063,4942,915,76
7,20260417H,Mount1,data007,spatial noise 4 R*/r/s,4.0,chunk2,manookinlab.protocols.SpatialNoise,61.77,339.90,2026-04-17 18:58:41,2026-04-17 20:00:27,20260417H/data007,202,239,3064,4943,913,19

In [2]:
exp_name = '2026-02-24_E_2'
df_exp = ra.get_exp_summary(exp_name)

In [3]:
df_exp.query('cell_label=="Cell6"')

,exp_name,prep_label,recording_technique,pipette_solution,cell_id,cell_label,cell_type,NDF,protocol_name,duration_minutes,minutes_since_start,start_time,end_time,cell_properties,group_label,experiment_id,prep_id,group_id,block_id,protocol_id
12,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.22,2026-02-24 16:53:29,2026-02-24 16:53:31,{'type': 'horizontal'},Control,186,215,2827,4310,2
13,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.42,2026-02-24 16:53:41,2026-02-24 16:53:43,{'type': 'horizontal'},Control,186,215,2827,4311,2
14,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.23,103.18,2026-02-24 16:54:15,2026-02-24 16:54:29,{'type': 'horizontal'},Control,186,215,2827,4312,73
15,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.50,2026-02-24 16:54:33,2026-02-24 16:54:48,{'type': 'horizontal'},Control,186,215,2827,4313,73
16,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.82,2026-02-24 16:54:52,2026-02-24 16:55:07,{'type': 'horizontal'},Control,186,215,2827,4314,73
17,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Expan...,0.85,104.83,2026-02-24 16:55:17,2026-02-24 16:56:08,{'type': 'horizontal'},Control,186,215,2827,4315,71
18,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Contr...,0.78,105.82,2026-02-24 16:56:20,2026-02-24 16:57:07,{'type': 'horizontal'},Control,186,215,2827,4316,75
19,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,1.10,106.98,2026-02-24 16:57:11,2026-02-24 16:58:17,{'type': 'horizontal'},Control,186,215,2827,4317,9
20,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,2.18,109.18,2026-02-24 16:58:18,2026-02-24 17:00:29,{'type': 'horizontal'},Control,186,215,2827,4318,9
21,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,111.13,2026-02-24 17:00:45,2026-02-24 17:02:26,{'type': 'horizontal'},Control,186,215,2827,4319,91
22,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,112.87,2026-02-24 17:02:29,2026-02-24 17:04:10,{'type': 'horizontal'},Control,186,215,2827,4320,91
23,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.70,113.65,2026-02-24 17:04:15,2026-02-24 17:04:57,{'type': 'horizontal'},Control,186,215,2827,4321,92
24,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.68,114.37,2026-02-24 17:04:59,2026-02-24 17:05:40,{'type': 'horizontal'},Control,186,215,2827,4322,92
25,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,116.08,2026-02-24 17:05:42,2026-02-24 17:07:23,{'type': 'horizontal'},Control,186,215,2827,4323,91

In [5]:
rb = ra.SCResponseBlock(exp_name, 4321, b_LED=True)

Initializing ResponseBlock for 2026-02-24_E_2 block 4321
Loading Amp1 data from /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/2026-02-24_E_2.h5 ...
Loaded (10, 40000) amp_data.

## Doves stim regen

In [4]:
doves_bid = 4317
sb = ra.StimBlock(exp_name, doves_bid)

Initializing StimBlock for 2026-02-24_E_2 block 4317
For Rig E 2026-02-24_E_2, assuming ConfocalWithLightCrafterAbove rig config:
{'disp_type': 'LCR', 'mu_per_pixel': 1.3, 'n_ht': 1140, 'n_wt': 1824, 'mean_frame_rate': 60.0}

In [5]:
sb.df_epochs

,epoch_index,imageName,subjectName,backgroundIntensity,stimulusIndex,exp_name,group_label,protocol_name,frame_times_ms,epoch_parameters,preTime,stimTime,tailTime,experiment_id,group_id,block_id,protocol_id,epoch_id
0,0,imk00031.iml,ACB2.eye,0.353622,2.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286233
1,1,imk00034.iml,ABT2.eye,0.164178,6.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286234
2,2,imk00037.iml,ACB2.eye,0.152617,12.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286235
3,3,imk00047.iml,ACB2.eye,0.183976,18.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286236
4,4,imk00053.iml,AV2.eye,0.230272,24.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286237
5,5,imk00054.iml,BSQ2.eye,0.285867,30.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286238
6,6,imk00060.iml,CS2.eye,0.144705,40.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286239
7,7,imk00063.iml,CLM2.eye,0.097741,50.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286240

In [7]:
sb.regenerate_stimulus(
    str_manookin_pkg_dir='/Users/riekelabbackup/Desktop/Vyom/stim_packages/manookin-package',
    d_display=sb.d_display,
    verbose=False)

Regenerating stimulus for epochs: [0, 1, 2, 3, 4, 5, 6, 7] in block: 4317
Using regeneration function: make_all_doves_movies
Processing epoch 1/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 12.47it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.25it/s]

Processing epoch 2/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 25.43it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.14it/s]

Processing epoch 3/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 22.37it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 68.63it/s]

Processing epoch 4/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.56it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 49.99it/s]

Processing epoch 5/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 24.08it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.90it/s]

Processing epoch 6/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.21it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 70.08it/s]

Processing epoch 7/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 27.00it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 63.77it/s]

Processing epoch 8/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 21.89it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 68.16it/s]

Regenerated stimulus with keys: ['movies', 'image_names', 'images']

In [25]:
import sys
sys.path.append('/Users/riekelabbackup/Desktop/Vyom/RetinAnalysis/src/retinanalysis/utils/')
import regen
import importlib
importlib.reload(regen)

In [26]:
type(sb.df_epochs.iloc[0])

pandas.core.series.Series

In [28]:
d_test = regen.make_all_doves_movies(
    sb.df_epochs, 
    '/Users/riekelabbackup/Desktop/Vyom/stim_packages/manookin-package',
    sb.d_display,
    verbose=False
)

Processing epoch 1/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 17.81it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 62.59it/s]

Processing epoch 2/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 20.06it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 74.46it/s]

Processing epoch 3/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 24.46it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.18it/s]

Processing epoch 4/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.62it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 74.52it/s]

Processing epoch 5/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.51it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 73.62it/s]

Processing epoch 6/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 22.44it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 70.25it/s]

Processing epoch 7/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.24it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.09it/s]

Processing epoch 8/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.05it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.12it/s]