# Debugging LED stim, and doves movie regen
VR March 2026

In [1]:
import retinanalysis as ra

[2026-03-05 17:49:28,734][INFO]: DataJoint 0.14.4 connected to root@127.0.0.1:3306

In [2]:
exp_name = '2026-02-24_E_2'
df_exp = ra.get_exp_summary(exp_name)

In [3]:
df_exp.query('cell_label=="Cell6"')

,exp_name,prep_label,recording_technique,pipette_solution,cell_id,cell_label,cell_type,NDF,protocol_name,duration_minutes,minutes_since_start,start_time,end_time,cell_properties,group_label,experiment_id,prep_id,group_id,block_id,protocol_id
12,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.22,2026-02-24 16:53:29,2026-02-24 16:53:31,{'type': 'horizontal'},Control,186,215,2827,4310,2
13,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.42,2026-02-24 16:53:41,2026-02-24 16:53:43,{'type': 'horizontal'},Control,186,215,2827,4311,2
14,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.23,103.18,2026-02-24 16:54:15,2026-02-24 16:54:29,{'type': 'horizontal'},Control,186,215,2827,4312,73
15,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.50,2026-02-24 16:54:33,2026-02-24 16:54:48,{'type': 'horizontal'},Control,186,215,2827,4313,73
16,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.82,2026-02-24 16:54:52,2026-02-24 16:55:07,{'type': 'horizontal'},Control,186,215,2827,4314,73
17,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Expan...,0.85,104.83,2026-02-24 16:55:17,2026-02-24 16:56:08,{'type': 'horizontal'},Control,186,215,2827,4315,71
18,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Contr...,0.78,105.82,2026-02-24 16:56:20,2026-02-24 16:57:07,{'type': 'horizontal'},Control,186,215,2827,4316,75
19,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,1.10,106.98,2026-02-24 16:57:11,2026-02-24 16:58:17,{'type': 'horizontal'},Control,186,215,2827,4317,9
20,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,2.18,109.18,2026-02-24 16:58:18,2026-02-24 17:00:29,{'type': 'horizontal'},Control,186,215,2827,4318,9
21,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,111.13,2026-02-24 17:00:45,2026-02-24 17:02:26,{'type': 'horizontal'},Control,186,215,2827,4319,91
22,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,112.87,2026-02-24 17:02:29,2026-02-24 17:04:10,{'type': 'horizontal'},Control,186,215,2827,4320,91
23,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.70,113.65,2026-02-24 17:04:15,2026-02-24 17:04:57,{'type': 'horizontal'},Control,186,215,2827,4321,92
24,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.68,114.37,2026-02-24 17:04:59,2026-02-24 17:05:40,{'type': 'horizontal'},Control,186,215,2827,4322,92
25,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,116.08,2026-02-24 17:05:42,2026-02-24 17:07:23,{'type': 'horizontal'},Control,186,215,2827,4323,91

In [5]:
rb = ra.SCResponseBlock(exp_name, 4321, b_LED=True)

Initializing ResponseBlock for 2026-02-24_E_2 block 4321
Loading Amp1 data from /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/2026-02-24_E_2.h5 ...
Loaded (10, 40000) amp_data.

## Doves stim regen

In [4]:
doves_bid = 4317
sb = ra.StimBlock(exp_name, doves_bid)

Initializing StimBlock for 2026-02-24_E_2 block 4317
For Rig E 2026-02-24_E_2, assuming ConfocalWithLightCrafterAbove rig config:
{'disp_type': 'LCR', 'mu_per_pixel': 1.3, 'n_ht': 1140, 'n_wt': 1824, 'mean_frame_rate': 60.0}

In [5]:
sb.df_epochs

,epoch_index,imageName,subjectName,backgroundIntensity,stimulusIndex,exp_name,group_label,protocol_name,frame_times_ms,epoch_parameters,preTime,stimTime,tailTime,experiment_id,group_id,block_id,protocol_id,epoch_id
0,0,imk00031.iml,ACB2.eye,0.353622,2.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286233
1,1,imk00034.iml,ABT2.eye,0.164178,6.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286234
2,2,imk00037.iml,ACB2.eye,0.152617,12.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286235
3,3,imk00047.iml,ACB2.eye,0.183976,18.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286236
4,4,imk00053.iml,AV2.eye,0.230272,24.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286237
5,5,imk00054.iml,BSQ2.eye,0.285867,30.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286238
6,6,imk00060.iml,CS2.eye,0.144705,40.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286239
7,7,imk00063.iml,CLM2.eye,0.097741,50.0,2026-02-24_E_2,Control,manookinlab.protocols.DovesMovie,"[0.0, 17.0, 34.0, 50.0, 67.0, 84.0, 100.0, 117...","{'NDF': 0.0, 'amp': 'Amp1', 'gain': None, 'ndf...",250.0,6000.0,500.0,186,2827,4317,9,286240

In [7]:
sb.regenerate_stimulus(
    str_manookin_pkg_dir='/Users/riekelabbackup/Desktop/Vyom/stim_packages/manookin-package',
    d_display=sb.d_display,
    verbose=False)

Regenerating stimulus for epochs: [0, 1, 2, 3, 4, 5, 6, 7] in block: 4317
Using regeneration function: make_all_doves_movies
Processing epoch 1/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 12.47it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.25it/s]

Processing epoch 2/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 25.43it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.14it/s]

Processing epoch 3/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 22.37it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 68.63it/s]

Processing epoch 4/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.56it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 49.99it/s]

Processing epoch 5/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 24.08it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 69.90it/s]

Processing epoch 6/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.21it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 70.08it/s]

Processing epoch 7/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 27.00it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 63.77it/s]

Processing epoch 8/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 21.89it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 68.16it/s]

Regenerated stimulus with keys: ['movies', 'image_names', 'images']

In [25]:
import sys
sys.path.append('/Users/riekelabbackup/Desktop/Vyom/RetinAnalysis/src/retinanalysis/utils/')
import regen
import importlib
importlib.reload(regen)

In [26]:
type(sb.df_epochs.iloc[0])

pandas.core.series.Series

In [28]:
d_test = regen.make_all_doves_movies(
    sb.df_epochs, 
    '/Users/riekelabbackup/Desktop/Vyom/stim_packages/manookin-package',
    sb.d_display,
    verbose=False
)

Processing epoch 1/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 17.81it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 62.59it/s]

Processing epoch 2/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 20.06it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 74.46it/s]

Processing epoch 3/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 24.46it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.18it/s]

Processing epoch 4/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.62it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 74.52it/s]

Processing epoch 5/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.51it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 73.62it/s]

Processing epoch 6/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 22.44it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 70.25it/s]

Processing epoch 7/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.24it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.09it/s]

Processing epoch 8/8

Generating frames: 100%|██████████| 12/12 [00:00<00:00, 26.05it/s]
Downsampling frames: 100%|██████████| 12/12 [00:00<00:00, 71.12it/s]